### ISSUE TITLE
question: How to make invariant that requires an expected version if the aggregate does exist?

### ISSUE THREAD

**Issue by TomKaltz** [Rotorsoft/eventually-monorepo#44]
When using the express app, I would like to be able to require the expectedVersion(If-Match) for certain aggregate commands.  The expectedVersion seems not to be exposed anywhere in the the aggregate api.  Is there another way to do this?

**Comment by Rotorsoft** [comment]
Hi Tom

Please look at this block that builds the internal command from express requests, including if-match headers:

https://github.com/Rotorsoft/eventually-monorepo/blob/77ba11bb591f9fa8302d8aa98bec6f010d04ce46/libs/eventually-express/src/handlers.ts#L155

Hope it helps!

**Comment by TomKaltz** [comment]
The issue is that in the aggregate implementation, the business rules don't have access to the expectedVersion in either the ```given``` or ```on``` declarations.  What I'd like to do is require expectedVersion for certain commands so that I can granularly constrain concurrency issues based on what is being commanded of the aggregate.  Do you think exposing expectedVersion to the aggregate commandhandler is appropriate for this use case?

**Comment by Rotorsoft** [comment]
The framework handles concurrency automatically. All you have to do is pass the expectedVersion as part of the command arguments.

**Comment by TomKaltz** [comment]
Yes but there is no way to enforce the requirement to use exepectedVersion.  If you don't specify expectedVersion when calling the command, it will run the command with no concurrency check.  Perhaps it's an anti-pattern but Ideally we should be able to enforce the requirement of expectedVersion in an aggregate invariant per command.

**Comment by Rotorsoft** [comment]
if you don't provide the expected version when invoking the command (via headers or client port), it means you don't care as long as no other user is mutating your aggregate in the middle of your transaction.... this is enforced here:

https://github.com/Rotorsoft/eventually-monorepo/blob/77ba11bb591f9fa8302d8aa98bec6f010d04ce46/libs/eventually/src/handlers.ts#L130

**Comment by TomKaltz** [comment]
> if you don't provide the expected version when invoking the command (via headers or client port), it means you don't care as long as no other user is mutating your aggregate in the middle of your transaction.... this is enforced here:

I'd like to revisit this.  It would be nice to have an option to be able to allow concurrent commands to an aggregate.

Currently fallback optimistic concurrency control is enforced here.... 
https://github.com/Rotorsoft/eventually-monorepo/blob/master/libs/eventually/src/handlers/commit.ts#L36

I understand this would allow possible duplicate event versions to get written to the store but again it would be really nice to somehow allow this at the aggregate or even command level as an option to users as there are certain situations where concurrent writes would be acceptable to an aggregate.  Your thoughts @Rotorsoft?

**Comment by Rotorsoft** [comment]
You don't want duplicate versions, and the framework enforces this rule with optimistic concurrency. Can you describe the type of scenario you are considering in detail? In event sourcing, concurrent writes are serialized to maintain events in a strict deterministic order... but you can always find high-frequency scenarios where you might want to optimize this process via internal retries, around aggregate boundaries, etc. This framework is not considering any of these edge cases yet, mostly focusing on simplicity and usability for general applications, but I can see the possibility of a simple retry strategy when concurrency errors are found and a specific expected version is not required.

**Comment by TomKaltz** [comment]
At first I thought duplicate event versions and concurrent writes would be fine but I also just realized that the snapshot returned from a command would be incorrect in a concurrent write situation.  I see that other event store frameworks allow ignoring concurrency but I think you’re right to require concurrency control for reducible artifacts in eventually.
