### ISSUE TITLE
Make monorepo more friendly for forking/contribution

### ISSUE THREAD

**Issue by TomKaltz** [Rotorsoft/eventually-monorepo#46]
**Describe the bug**
Currently the build task fails on a fork due to NPM integration.  The error is ```Usage Error: Environment variable not found (NPM_TOKEN)``` and it's because there isn't a proper NPM_TOKEN in the .yarnrc.yml.  Is there a way around this for contributors other than removing the npm entries in .yarnrc.yml?

**To Reproduce**
1. Fork this monorepo
2. clone to the fork
3. run ```yarn build```
4. See error ```Usage Error: Environment variable not found (NPM_TOKEN)```

**Expected behavior**
I expect to be able to build the fork on my local machine.

**Desktop (please complete the following information):**
 - OS: Windows 11 Home

**Comment by Rotorsoft** [comment]
Hey Tom

All you need is to export an NPM_TOKEN to your local env, it doesn't have to be a valid one, it's only used to publish to NPM

`export NPM_TOKEN=xxxxxxxxxxxxxxxx`

Let me know ;-)

**Comment by TomKaltz** [comment]
Ok that worked with the NPM_TOKEN env variable!  Now the issue I'm having is I can't use the local monorepo libs as a local dependencies in another project due to how workspaces work.  The workspaces don't resolve.  Do you know a workaround for this?

**Comment by Rotorsoft** [comment]
I don't... I guess that's the idea of the mono repo though, to have all libs inside the same mono-repo project. You can add your lib to the /libs folder and use the same patterns I'm using there..., but you will have to tweak the publishing workflow if you want to publish your lib to another npm account. 

Let me know if you find a better way to collaborate with mono-repos and we can plan the upgrade.

**Comment by TomKaltz** [comment]
Thanks Roger, I did figure out I can use the monorepo libs folder as a workspace in my other project.  Now I should be able to easily develop my eventually-firestore lib and contribute it back!
