### ISSUE TITLE
question: external side effects

### ISSUE THREAD

**Issue by TomKaltz** [Rotorsoft/eventually-monorepo#49]
This may be more of a philosophical discussion but where are external side-effects like email notification meant to be handled in an eventually service?

Would a process manager or policy call a system or could the process manager possibly just handle the side effect in the event handler?

**Comment by Rotorsoft** [comment]
My default answer is almost always "it depends" 😅. How much coupling do you want to have between your core subdomains and the services delivering notifications? Do you need an intermediary mapping service to decide how and when to deliver notifications so your internal policies don't have to know all channels, service specifics, etc. This of course adds more layers and complexity, so up to you. This has nothing to do with eventually, it's a general design trade off you will find everywhere.

Hope it helps, considering I don't have more details about your system 👍
