### ISSUE TITLE
Feature: cross-service commands

### ISSUE THREAD

**Issue by TomKaltz** [Rotorsoft/eventually-monorepo#51]
For service orchestration, I’m pondering the best way for one service’s process manager to call another service’s command. Perhaps each service could generate and serve an auto-generated sdk that other services could consume?  Any other ideas?  

Obviously the decision to use orchestration for certain processes creates a tighter coupling but is required for certain business requirements.

**Comment by Rotorsoft** [comment]
I try to avoid this pattern, but when necessary I just use an axios helper function to call commands, something like the HTTP client found in the eventually-express package. 
This is needed though when policies read from projections, I use the axios approach too.

If you build the ESML model of your services, you will clearly see the blue, green, and orange arrows showing inter-context coupling... find your compromise, but try to avoid blue ones

I just deployed a new feature in the ESML create-eventually-app generator to deal with something like this... generating vscode tasks and docker-compose config to run all services in your dev env.
