### ISSUE TITLE
A command that must not fail

### ISSUE THREAD

**Issue by TomKaltz** [Rotorsoft/eventually-monorepo#57]
How should we handle a command that must not fail for any reason?  The scenario I'm working with now is webhook catching....if there is a concurrency error while committing the webhook event, the command can fail and the webhook event will not be stored.  Any recommendation for a scenario like this?  Could something like this be handled by the framework or should I build a custom express endpoint with retry or some sort of dead letter mechanism built there?

**Comment by Rotorsoft** [comment]
You should always design your system around potential command failures. Events represent the things that already "happened", commands are the things you are trying to accomplish. Integration reliability (like when using webhooks) is achieved by consuming from a persistent event stream. Some producers will provide this functionality with retries, etc but sometimes you have to store the input stream and implement this mechanism somehow, you can find examples in the broker service (not a finished product though)
