### ISSUE TITLE
side effects during replay

### ISSUE THREAD

**Issue by TomKaltz** [Rotorsoft/eventually-monorepo#63]
How should we handle/avoid side-effects during replay?

**Comment by TomKaltz** [comment]
After more thought about this it would seem there is one solution…only reset the subscription watermark of artifacts that don’t produce side-effects.  This seems the most straightforward.  Perhaps there is not a need for anything more complex at the framework level.

**Comment by Rotorsoft** [comment]
You should be able to replay projections without side effects, policies on the other hand are trickier and not good candidates for replays when they produce side effects, but it always depends on specific scenarios.
