### ISSUE TITLE
Separate snapshot store

### ISSUE THREAD

**Issue by TomKaltz** [Rotorsoft/eventually-monorepo#64]
Should the snapshot store be a separate port? Since business logic can have bugs or will need to be changed over time, snapshots may need to be dropped.  Another scenario I can think of is being able to drop previous snapshots to save on storage costs since they any previous snapshots could be no longer relevant depending on business requirements. 

Currently the snapshots are stored in-stream which would cause non-contiguous versioning if a snapshot had to be deleted after a bugfix.  I’m not sure that’s even a problem but something that came to mind.

Also, storing the snapshot in-stream can fail due to concurrency, which probably isn’t a big deal either but wanted to note.

**Comment by Rotorsoft** [comment]
I'm not sure about the type of scenarios you are considering here, but looks like you are trying to backfill aggregate snapshots after fixing bugs or adding features that modify the state. From an accountant's perspective, changing history is usually not desired, and you should probably consider "tagging" the stream when you introduce breaking changes in the aggregate logic. The goal is always the same, being able to replay the aggregate through history, considering bugs and versions as those happened, and you can always use snapshots to shortcut (or tag) the starting point. 

If your goal is to save on storage costs, try another accounting strategy => "closing the books" every year or whatever feels like the proper retention time. 

The framework should be consistent when storing events + snapshots, using ACID to avoid racing conditions.

**Comment by TomKaltz** [comment]
These are hypothetical scenarios but consider when a state snapshot is written with bad aggregate logic.  (Of course the events could have been written incorrectly, which is another problem that could cause a loss of historical facts/data in the system)  But when the aggregate internal state calculation is corrected and deployed, the aggregate will not have access to the events before the "bad" snapshot, rendering the log of historical facts useless in deriving a correct current aggregate state.  The current drain implementation does not have the option to ignore snapshots and build the state from and through the complete stream history.

**Comment by TomKaltz** [comment]
After reading the comment [here](https://github.com/Rotorsoft/eventually-monorepo/issues/61#issuecomment-1885758628) I realize that a manual way of correcting toxic snapshots would be to create a script to manually load() the stream of each aggregate, ignoring previous snapshots and rebuilding a new correct snapshot and committing it to the stream.

**Comment by Rotorsoft** [comment]
We are probably looking at edge cases here, but you can always recreate streams with options to remove snapshots or merge/split sub-streams... for example, when aggregate logic or aggregate boundaries are redefined. These operations are usually maintenance scripts such as the one you are suggesting.

**Comment by TomKaltz** [comment]
Very interesting discussion. There are trade-offs in whichever way snapshots are managed.  I share the same apprehension as described [here](https://github.com/rbanks54/microcafe/issues/6#issuecomment-285809608), but having snapshots in the same stream does make the system simpler and perhaps more performant in aggregate hydration.

I am though running into the issue of stream contention when a snapshot is attempted to be written.  My use-case involves catching webhooks events to various streams and sometimes two webhook commands can occur on the same stream very close together in time.  If the first webhook triggers a snapshot but the second webhook write wins on the race to make that commit, the snapshot will fail due to concurrency error.  (I handle the inverse with retry of the webhook command at the application level.)  Perhaps snapshotting should have built in retry?  Of course missing a snapshot is never a bad thing so I guess the errors can be ignored but this sort of contention seems like it can degrade application performance.

**Comment by Rotorsoft** [comment]
In that case, the last snapshot should win the race, all others should fail with concurrency errors. If you configure snapshots to occur every 100 event or so, this shouldn't be a big deal.
