### ISSUE TITLE
process-manager semantics

### ISSUE THREAD

**Issue by TomKaltz** [Rotorsoft/eventually-monorepo#68]
Process-managers never reduce on poll().  It seems that the reducible inputs events metadata are not added during build().

**Comment by TomKaltz** [comment]
After running the tests on my local machine I realize that the pm test does pass so it's probably something I'm doing in my InferProcessManager implementation.  I will investigate further and reopen if I can actually confirm a bug.

**Comment by TomKaltz** [comment]
@Rotorsoft I figured out what I was doing wrong.  I didn't realize that Process Managers can only reduce over events that were caused by that Process Manager in the first place.  Do you think there could be any way to check this at the typescript level or perhaps at the build() level and throw errors if the PM contains reducer keys that could never be fired?

**Comment by Rotorsoft** [comment]
hey @TomKaltz... not sure how to answer this without a concrete example, but sounds like you are on the right track. In general, the process manager implementation in eventually is a little tricky... I hope this is captured in the documentation (might need more details though)

```typescript
/**
 * Process managers are policies with reducible state, used to expand a consistency boundary around aggregates.
 * Each process is an actor with reduced state from the `O`utput events emitted by the aggregates it encapsulates.
 * - `schemas` for message validation and documentation
 * - `actor` actor id resolvers from input events
 * - `on` event handlers
 */
export type ProcessManager<
  S extends State = State,
  C extends Messages = Messages,
  E extends Messages = Messages,
  O extends Messages = Messages
> = Reducible<S, O> & {
  schemas: ProcessManagerSchemas<S, C, E>;
  actor: { [K in keyof E]: ActorHandler<E, K> };
  on: {
    [K in keyof E]: (
      event: CommittedEvent<Pick<E, K>>,
      state: Readonly<S>
    ) => Promise<Message<C> | undefined> | undefined;
  };
};
```
The trick is in understanding the `O`utput type, and the reduced state of output events (emitted by the aggregates encapsulated by the process manager)... you can read more about this here: https://medium.com/@roger.torres/consistency-boundaries-with-event-sourcing-e3062e4f52c1

**Comment by TomKaltz** [comment]
Wish I had found your blog sooner!  It was immensely helpful in explaining the design semantics of this particular flavor of process manager.  I previously noticed the term "Output" but didn't understand it quite correctly.  A link to that blog post in the docs would be a good idea since it's a little tricky as you said.

I've run into another gotcha, learning that it's fatal to a process manager artifact to subscribe an ```on``` handler to the same event name as a reducible Output event.  Doing so will cause the event count compared with the database to be incorrect since the resulting event will be tagged with the same actor causation.  This will cause a permanent actor concurrency error loop until the poison event is either deleted or the actor id is removed from its metadata.  At the very least the footgun should be documented.  This also reminds me of #58 and further highlights the need for a circuit breaker for subscriptions.

**Comment by Rotorsoft** [comment]
You can design infinite loops everywhere, from low-level language constructs to the modeling surface (like in this case). This is not a particular problem of "eventually PMs", you can design loops with plain aggregates and policies too...  feels like the responsibility for detecting these loops would only overcomplicate things internally. The modeling surface is usually the best place to manage most of the complexity.
